version: "3.9"

volumes:
  userapp:
  bookapp:
  orderapp:
  frontendapp:

services:
  user-service:
    container_name: user-service-container
    build:
      context: ../user
    ports:
      - "5001:5001"
    volumes:
      - userapp:/userapp
    restart: always

  book-service:
    container_name: book-service-container
    build:
      context: ../book
    ports:
      - "5002:5002"
    volumes:
      - bookapp:/bookapp
    restart: always

  order-service:
    container_name: order-service-container
    build:
      context: ../order
    ports:
      - "5003:5003"
    volumes:
      - orderapp:/orderapp
    restart: always

  frontend-service:
    container_name: frontend-service-container
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - frontendapp:/frontendapp
    restart: always

